import React, { useState, useEffect, useRef } from 'react';
import { 
  FileText, 
  FileSpreadsheet, 
  FlaskConical, 
  Award, 
  Mic, 
  MicOff, 
  Sparkles, 
  Printer, 
  AlertCircle, 
  CheckCircle2, 
  Layers, 
  User, 
  Calendar, 
  ShieldAlert, 
  RefreshCw,
  HelpCircle,
  FileCheck,
  Volume2,
  Trash2,
  Info,
  Radio
} from 'lucide-react';
import { DocumentType, PatientInfo, ProcessedDocumentResult } from '../types';
import { workspaceEngine, MAGIC_GRAPHIC_TEMPLATES } from '../api/workspaceEngine';
import { DocumentPreviewModal } from './DocumentPreviewModal';
import { BrandLogo } from './BrandLogo';
import { normalizeClinicalPhonetics } from '../utils/phoneticDictionary';
import { ClinicalConflictResolver } from '../cloud/ClinicalConflictResolver';

interface Props {
  onDocumentCreated?: (doc: ProcessedDocumentResult) => void;
}

// Helper to transform clinical voice commands to standard medical typography
const formatClinicalSpeech = (text: string): string => {
  let formatted = text;
  formatted = formatted
    // Newlines / paragraphs
    .replace(/\b(punto y aparte|párrafo aparte|nueva línea|nuevo párrafo)\b/gi, '\n\n')
    .replace(/\b(punto y seguido)\b/gi, '. ')
    .replace(/\b(punto final|punto)\b/gi, '. ')
    .replace(/\b(dos puntos)\b/gi, ': ')
    .replace(/\b(punto y coma)\b/gi, '; ')
    .replace(/\b(coma)\b/gi, ', ')
    .replace(/\b(signo de interrogación|interrogación)\b/gi, '?')
    .replace(/\b(abrir paréntesis|abre paréntesis)\b/gi, ' (')
    .replace(/\b(cerrar paréntesis|cierra paréntesis)\b/gi, ') ')
    .replace(/\b(abrir comillas|abre comillas)\b/gi, ' "')
    .replace(/\b(cerrar comillas|cierra comillas)\b/gi, '" ')
    .replace(/\b(guion|guión)\b/gi, ' - ')
    .replace(/\b(número uno|ítem uno)\b/gi, '1. ')
    .replace(/\b(número dos|ítem dos)\b/gi, '2. ')
    .replace(/\b(número tres|ítem tres)\b/gi, '3. ')
    .replace(/\b(número cuatro|ítem cuatro)\b/gi, '4. ')
    .replace(/\b(número cinco|ítem cinco)\b/gi, '5. ')
    .replace(/\s{2,}/g, ' ')
    .replace(/\s+([.,;:?!])/g, '$1');
  return formatted;
};

// Removes stutter, echoes, and immediate repeating phrases/words generated by Chrome Web Speech API
const cleanStutterAndEchoes = (text: string): string => {
  let cleaned = text;
  let prev = '';
  let iterations = 0;
  // Up to 5 passes to resolve nested repetition artifacts
  while (cleaned !== prev && iterations < 5) {
    prev = cleaned;
    iterations++;
    // Remove repeated multi-word sequences (2 to 8 words), e.g. "buenas tardes buenas tardes" -> "buenas tardes"
    cleaned = cleaned.replace(/\b((?:[\wáéíóúñÁÉÍÓÚÑ]+\s+){1,8}[\wáéíóúñÁÉÍÓÚÑ]+)(?:\s+\1\b)+/gi, '$1');
    // Remove single words repeated 3+ times, e.g. "hola hola hola" -> "hola"
    cleaned = cleaned.replace(/\b([\wáéíóúñÁÉÍÓÚÑ]+)(?:\s+\1\b){2,}/gi, '$1');
  }
  return cleaned.replace(/\s{2,}/g, ' ').trim();
};

// Fusión inteligente por solapamiento: evita duplicar fragmentos si Chrome re-emite la cola
export const mergeSpeechTranscripts = (existingText: string, newChunk: string): string => {
  const cleanChunk = cleanStutterAndEchoes(newChunk.trim());
  const cleanExisting = existingText.trim();

  if (!cleanChunk) return cleanExisting;
  if (!cleanExisting) return cleanChunk;

  // Si el texto previo ya termina exactamente con la frase dictada, no hacer nada
  if (cleanExisting.endsWith(cleanChunk) || cleanExisting.toLowerCase().endsWith(cleanChunk.toLowerCase())) {
    return cleanExisting;
  }

  // Comprobar solapamiento de palabras (overlap) entre el final del existente y el inicio del nuevo
  const existingWords = cleanExisting.split(/\s+/);
  const newWords = cleanChunk.split(/\s+/);

  const maxCheck = Math.min(existingWords.length, newWords.length, 8);
  for (let len = maxCheck; len > 0; len--) {
    const endSlice = existingWords.slice(-len).join(' ').toLowerCase();
    const startSlice = newWords.slice(0, len).join(' ').toLowerCase();
    if (endSlice === startSlice) {
      // Se detectó solapamiento: se descartan las palabras repetidas del inicio del chunk
      const mergedWords = [...existingWords, ...newWords.slice(len)];
      return cleanStutterAndEchoes(mergedWords.join(' '));
    }
  }

  // Si no hay solapamiento, simplemente se concatena con separación adecuada
  return `${cleanExisting} ${cleanChunk}`;
};

export const MedicalForm: React.FC<Props> = ({ onDocumentCreated }) => {
  // Document Type State
  const [docType, setDocType] = useState<DocumentType>('recipe');

  // Patient Info State
  const [patient, setPatient] = useState<PatientInfo>({
    fullName: 'Alejandro Carrillo Pérez',
    idType: 'V',
    nationalId: '18.942.510',
    age: '38',
    gender: 'M',
    allergies: 'Penicilina (Reacción urticariana)',
    phone: '0414-2394012',
    email: 'acarrillo@email.com',
  });

  // Clinical Note Text
  const [rawNote, setRawNote] = useState<string>(
    `Dx: Rinofaringitis aguda complicada + Cuadro febril de 48h.\n` +
    `1. Azitromicina 500mg vía oral cada 24 horas por 3 días.\n` +
    `2. Ibuprofeno 600mg cada 8 horas por 5 días con las comidas.\n` +
    `3. Cetirizina 10mg una tableta nocturna por 7 días.\n` +
    `Indicaciones: Reposo por 3 días continuos. Abundante hidratación oral.`
  );

  // Voice Dictation (Web Speech API) - Multi-layer Anti-Duplication Engine
  const [isListening, setIsListening] = useState(false);
  const [interimTranscript, setInterimTranscript] = useState('');
  const [speechSupported, setSpeechSupported] = useState(true);
  const [speechLang, setSpeechLang] = useState<'es-VE' | 'es-419' | 'es-ES'>('es-VE');
  const [speechError, setSpeechError] = useState<string | null>(null);
  const [showVoiceHelp, setShowVoiceHelp] = useState(false);
  
  const recognitionRef = useRef<any>(null);
  const shouldListenRef = useRef(false);
  const textareaRef = useRef<HTMLTextAreaElement>(null);
  const processedIndicesRef = useRef<Set<number>>(new Set());
  const lastCommittedTextRef = useRef('');
  const lastCommittedTimeRef = useRef(0);
  const rawNoteRef = useRef(rawNote);
  rawNoteRef.current = rawNote;

  // Processing & Modal State
  const [isProcessing, setIsProcessing] = useState(false);
  const [processingStage, setProcessingStage] = useState('');
  const [processedDoc, setProcessedDoc] = useState<ProcessedDocumentResult | null>(null);
  const [showPreviewModal, setShowPreviewModal] = useState(false);
  const [validationError, setValidationError] = useState<string | null>(null);

  // Stop listening cleanly and release hardware
  const stopListening = () => {
    shouldListenRef.current = false;
    setIsListening(false);
    setInterimTranscript('');
    processedIndicesRef.current.clear();
    lastCommittedTextRef.current = '';
    lastCommittedTimeRef.current = 0;
    if (recognitionRef.current) {
      try {
        recognitionRef.current.onstart = null;
        recognitionRef.current.onresult = null;
        recognitionRef.current.onerror = null;
        recognitionRef.current.onend = null;
        recognitionRef.current.abort();
      } catch {
        // ignore
      }
      recognitionRef.current = null;
    }
  };

  // Factory to create a clean, non-leaking SpeechRecognition session
  const createAndStartRecognition = () => {
    if (!shouldListenRef.current) return;

    const SpeechRecognition = 
      (window as any).SpeechRecognition || 
      (window as any).webkitSpeechRecognition;

    if (!SpeechRecognition) {
      setSpeechSupported(false);
      setSpeechError('Tu navegador no soporta reconocimiento de voz nativo (Web Speech API). Te recomendamos Google Chrome o Microsoft Edge.');
      return;
    }

    // Clean up any stale prior instance
    if (recognitionRef.current) {
      try {
        recognitionRef.current.onstart = null;
        recognitionRef.current.onresult = null;
        recognitionRef.current.onerror = null;
        recognitionRef.current.onend = null;
        recognitionRef.current.abort();
      } catch {
        // ignore
      }
      recognitionRef.current = null;
    }

    // Android Chrome accumulates duplicates when continuous=true. Setting continuous=false on mobile solves this at source.
    const isMobile = /Android|iPhone|iPad|iPod|webOS|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent);
    const recognition = new SpeechRecognition();
    recognition.continuous = !isMobile;
    recognition.interimResults = true;
    recognition.lang = speechLang;

    recognition.onstart = () => {
      setIsListening(true);
      setSpeechError(null);
    };

    recognition.onresult = (event: any) => {
      let interim = '';

      for (let i = event.resultIndex; i < event.results.length; ++i) {
        const item = event.results[i];
        if (!item || !item[0]) continue;

        if (item.isFinal) {
          // Layer 1: Index tracking - never process the same index twice in this session
          if (processedIndicesRef.current.has(i)) {
            continue;
          }
          processedIndicesRef.current.add(i);

          const rawChunk = item[0].transcript?.trim() || '';
          if (!rawChunk) continue;

          // Layer 2: Debounce - ignore identical phrases received within 2.5 seconds
          const now = Date.now();
          if (
            rawChunk.toLowerCase() === lastCommittedTextRef.current.toLowerCase() &&
            now - lastCommittedTimeRef.current < 2500
          ) {
            continue;
          }

          lastCommittedTextRef.current = rawChunk;
          lastCommittedTimeRef.current = now;

          // Layer 3: Clean immediate repeated words / n-gram stutter (e.g. "buenas tardes buenas tardes")
          const cleaned = cleanStutterAndEchoes(rawChunk);
          if (!cleaned) continue;

          // Layer 4: Transform clinical voice commands into standard medical punctuation
          const formatted = formatClinicalSpeech(cleaned);

          // Layer 4b: Normalización fonética neuroquirúrgica (L4-L5, pregabalina, signos neurológicos)
          const normalized = normalizeClinicalPhonetics(formatted).normalizedText;

          // Layer 5: Suffix/prefix overlap merger into note to guarantee no repeating words
          setRawNote((prev) => mergeSpeechTranscripts(prev, normalized));
          setInterimTranscript('');
        } else {
          const t = item[0].transcript?.trim();
          if (t) {
            interim += (interim ? ' ' : '') + t;
          }
        }
      }

      if (interim) {
        setInterimTranscript(cleanStutterAndEchoes(interim));
      }
    };

    recognition.onerror = (event: any) => {
      console.warn('Speech recognition error:', event.error);
      if (event.error === 'no-speech') {
        // Natural speech pause
        return;
      }
      if (event.error === 'not-allowed') {
        shouldListenRef.current = false;
        setIsListening(false);
        setSpeechError('Permiso de micrófono denegado. Habilita los permisos de micrófono en la barra de tu navegador para dictar.');
        return;
      }
      if (event.error === 'audio-capture') {
        shouldListenRef.current = false;
        setIsListening(false);
        setSpeechError('No se encontró ningún micrófono conectado en tu equipo.');
        return;
      }
      if (event.error === 'network') {
        setSpeechError('Error de red al procesar voz. Verifica tu conexión a internet.');
      }
    };

    recognition.onend = () => {
      setInterimTranscript('');
      processedIndicesRef.current.clear();

      // Auto-recover after pauses if user has not explicitly stopped
      if (shouldListenRef.current) {
        setTimeout(() => {
          if (shouldListenRef.current) {
            createAndStartRecognition();
          }
        }, 200);
      } else {
        setIsListening(false);
      }
    };

    recognitionRef.current = recognition;

    try {
      recognition.start();
    } catch (err: any) {
      console.warn('Recognition start exception:', err);
    }
  };

  const startListening = () => {
    setSpeechError(null);
    const SpeechRecognition = 
      (window as any).SpeechRecognition || 
      (window as any).webkitSpeechRecognition;

    if (!SpeechRecognition) {
      setSpeechSupported(false);
      setSpeechError('Tu navegador no soporta reconocimiento de voz nativo (Web Speech API). Te recomendamos Google Chrome o Microsoft Edge.');
      return;
    }

    shouldListenRef.current = true;
    lastCommittedTextRef.current = '';
    lastCommittedTimeRef.current = 0;
    processedIndicesRef.current.clear();
    createAndStartRecognition();
  };

  const toggleSpeech = () => {
    if (isListening) {
      stopListening();
    } else {
      startListening();
    }
  };

  // Check Web Speech API availability on mount and cleanup on unmount
  useEffect(() => {
    const SpeechRecognition = 
      (window as any).SpeechRecognition || 
      (window as any).webkitSpeechRecognition;

    if (!SpeechRecognition) {
      setSpeechSupported(false);
    }

    return () => {
      stopListening();
    };
  }, []);

  // If user switches dialect while recording, restart cleanly with new language
  useEffect(() => {
    if (shouldListenRef.current) {
      createAndStartRecognition();
    }
  }, [speechLang]);

  // Preset Clinical Examples
  const loadPreset = (type: 'respiratory' | 'trauma' | 'certificate') => {
    if (type === 'respiratory') {
      setDocType('recipe');
      setRawNote(
        `Dx: Faringoamigdalitis purulenta aguda + Fiebre 38.8°C.\n` +
        `1. Amoxicilina + Ácido Clavulánico 875/125mg vía oral cada 12 horas por 7 días.\n` +
        `2. Dexketoprofeno 25mg cada 8 horas según dolor por 4 días.\n` +
        `3. Gargarismos con solución salina tibia cada 6 horas.\n` +
        `Indicaciones: Reposo absoluto por 48 horas. Hidratación constante.`
      );
    } else if (type === 'trauma') {
      setDocType('report');
      setRawNote(
        `Dx: Esguince de tobillo derecho Grado II (Ligamento peroneoastragalino anterior).\n` +
        `Paciente refiere torcedura por inversión forzada durante práctica deportiva.\n` +
        `Plan:\n` +
        `1. Celecoxib 200mg una cápsula cada 12 horas por 7 días.\n` +
        `2. Aplicación de frío local crioterapia 15 min 3 veces al día.\n` +
        `3. Inmovilización con férula de tobillo y descarga de peso.\n` +
        `Laboratorio/Estudios: Resonancia Magnética de tobillo derecho sin contraste.`
      );
    } else {
      setDocType('certificate');
      setRawNote(
        `Dx: Cervicobraquialgia aguda post-traumática moderada.\n` +
        `Por medio de la presente se indica reposo médico estricto por 5 días continuos a partir de la presente fecha.\n` +
        `Tratamiento: Tiocolchicósido + Ketoprofeno oral cada 12 horas.\n` +
        `Control por consulta externa al término del reposo.`
      );
    }
  };

  // Submit Handler
  const handleProcessAndPrint = async () => {
    setValidationError(null);

    if (!patient.fullName.trim() || !patient.nationalId.trim()) {
      setValidationError('Por favor ingresa el nombre y la cédula del paciente.');
      return;
    }

    if (!rawNote.trim()) {
      setValidationError('Por favor escribe o dicta la nota médica antes de procesar.');
      return;
    }

    const blockCheck = ClinicalConflictResolver.isDocumentGenerationBlocked(patient.nationalId);
    if (blockCheck.blocked) {
      setValidationError(blockCheck.reason || 'Protección Médico-Legal Activa: La emisión de documentos está bloqueada porque existe un conflicto de sincronización concurrente pendiente de resolución.');
      return;
    }

    setIsProcessing(true);
    setProcessingStage('1/3: Estructurando diagnósticos y posología con Gemini AI...');

    try {
      setTimeout(() => {
        setProcessingStage('2/3: Inyectando datos en plantilla Google Docs de Magic Graphic...');
      }, 700);

      setTimeout(() => {
        setProcessingStage('3/3: Preservando sellos y exportando PDF listo para imprimir...');
      }, 1200);

      // Sincronizar con el endpoint de extracción de Gemini 2.5 Flash
      try {
        await fetch('/api/gemini/extract-clinical-summary', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            transcript: rawNote,
            currentData: { patient },
          }),
        });
      } catch (e) {
        console.warn('Backend sync warning:', e);
      }

      const result = await workspaceEngine.processMedicalDocument({
        patient,
        documentType: docType,
        rawClinicalNote: rawNote,
        templateId: MAGIC_GRAPHIC_TEMPLATES[docType].id,
        includeDigitalSignature: true,
        metadata: {
          doctorName: 'Dr. Samir Moucharrafie Naime',
          doctorLicence: 'MPPS: 61231 | CMEB: 5331 | RIF: V-12887723-3',
          clinicLocation: 'Centro Médico Quirúrgico CcMi (UCBL Lyon 1 - Francia)',
        },
      });

      setProcessedDoc(result);
      setShowPreviewModal(true);

      if (onDocumentCreated) {
        onDocumentCreated(result);
      }
    } catch (err: any) {
      console.error(err);
      setValidationError('Ocurrió un error al procesar el documento. Intenta nuevamente.');
    } finally {
      setIsProcessing(false);
      setProcessingStage('');
    }
  };

  return (
    <div id="medical-form-container" className="space-y-6 max-w-5xl mx-auto pb-12">
      {/* Top Banner: Status & Guidance */}
      <div className="bg-white border border-slate-200 rounded-2xl p-4 sm:p-5 shadow-sm flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
        <div className="flex items-center gap-3.5">
          <div className="w-12 h-12 rounded-xl bg-slate-50 border border-slate-200 p-1 flex items-center justify-center shrink-0 shadow-xs">
            <BrandLogo size={40} />
          </div>
          <div>
            <h2 className="text-base font-bold text-slate-900 flex items-center gap-2">
              Emisión de Papelería Médica Asistida
              <span className="px-2 py-0.5 text-[11px] font-semibold bg-blue-100 text-blue-800 rounded-full border border-blue-200">
                Magic Graphic Engine
              </span>
            </h2>
            <p className="text-xs text-slate-500">
              Escribe o dicta en lenguaje natural. El motor estructura el récipe y lo fusiona con la plantilla oficial de Google Docs.
            </p>
          </div>
        </div>

        {/* Quick Example Presets */}
        <div className="flex items-center gap-1.5 flex-wrap">
          <span className="text-[11px] text-slate-400 font-medium mr-1">Cargar Caso Rápido:</span>
          <button
            type="button"
            onClick={() => loadPreset('respiratory')}
            className="px-2.5 py-1 text-xs font-medium text-slate-700 bg-slate-100 hover:bg-slate-200 rounded-lg transition-colors cursor-pointer"
          >
            Faringitis
          </button>
          <button
            type="button"
            onClick={() => loadPreset('trauma')}
            className="px-2.5 py-1 text-xs font-medium text-slate-700 bg-slate-100 hover:bg-slate-200 rounded-lg transition-colors cursor-pointer"
          >
            Informe Trauma
          </button>
          <button
            type="button"
            onClick={() => loadPreset('certificate')}
            className="px-2.5 py-1 text-xs font-medium text-slate-700 bg-slate-100 hover:bg-slate-200 rounded-lg transition-colors cursor-pointer"
          >
            Reposo
          </button>
        </div>
      </div>

      {/* 1. DOCUMENT TYPE SELECTOR */}
      <div className="bg-white border border-slate-200 rounded-2xl p-5 shadow-sm space-y-3">
        <div className="flex items-center justify-between">
          <label className="text-xs font-bold text-slate-700 uppercase tracking-wider flex items-center gap-1.5">
            <Layers className="w-3.5 h-3.5 text-blue-600" />
            1. Seleccione el Tipo de Documento Médico
          </label>
          <span className="text-xs text-slate-500 font-mono">
            Plantilla: <strong className="text-slate-800">{MAGIC_GRAPHIC_TEMPLATES[docType].name}</strong>
          </span>
        </div>

        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
          {/* Récipe */}
          <button
            type="button"
            id="doc-type-recipe"
            onClick={() => setDocType('recipe')}
            className={`p-3.5 rounded-xl border text-left transition-all flex flex-col justify-between cursor-pointer ${
              docType === 'recipe'
                ? 'bg-blue-50/70 border-blue-600 shadow-sm ring-1 ring-blue-600/30'
                : 'bg-white border-slate-200 hover:border-slate-300 hover:bg-slate-50'
            }`}
          >
            <div className="flex items-center justify-between mb-2">
              <div className={`p-2 rounded-lg ${docType === 'recipe' ? 'bg-blue-600 text-white' : 'bg-slate-100 text-slate-600'}`}>
                <FileText className="w-4 h-4" />
              </div>
              {docType === 'recipe' && <CheckCircle2 className="w-4 h-4 text-blue-600" />}
            </div>
            <div>
              <span className="block text-sm font-bold text-slate-900">Récipe Médico</span>
              <span className="text-[11px] text-slate-500">Prescripción y Posología</span>
            </div>
          </button>

          {/* Informe Médico */}
          <button
            type="button"
            id="doc-type-report"
            onClick={() => setDocType('report')}
            className={`p-3.5 rounded-xl border text-left transition-all flex flex-col justify-between cursor-pointer ${
              docType === 'report'
                ? 'bg-blue-50/70 border-blue-600 shadow-sm ring-1 ring-blue-600/30'
                : 'bg-white border-slate-200 hover:border-slate-300 hover:bg-slate-50'
            }`}
          >
            <div className="flex items-center justify-between mb-2">
              <div className={`p-2 rounded-lg ${docType === 'report' ? 'bg-blue-600 text-white' : 'bg-slate-100 text-slate-600'}`}>
                <FileSpreadsheet className="w-4 h-4" />
              </div>
              {docType === 'report' && <CheckCircle2 className="w-4 h-4 text-blue-600" />}
            </div>
            <div>
              <span className="block text-sm font-bold text-slate-900">Informe Médico</span>
              <span className="text-[11px] text-slate-500">Especializado / Resumen</span>
            </div>
          </button>

          {/* Orden de Laboratorio */}
          <button
            type="button"
            id="doc-type-lab"
            onClick={() => setDocType('lab_order')}
            className={`p-3.5 rounded-xl border text-left transition-all flex flex-col justify-between cursor-pointer ${
              docType === 'lab_order'
                ? 'bg-blue-50/70 border-blue-600 shadow-sm ring-1 ring-blue-600/30'
                : 'bg-white border-slate-200 hover:border-slate-300 hover:bg-slate-50'
            }`}
          >
            <div className="flex items-center justify-between mb-2">
              <div className={`p-2 rounded-lg ${docType === 'lab_order' ? 'bg-blue-600 text-white' : 'bg-slate-100 text-slate-600'}`}>
                <FlaskConical className="w-4 h-4" />
              </div>
              {docType === 'lab_order' && <CheckCircle2 className="w-4 h-4 text-blue-600" />}
            </div>
            <div>
              <span className="block text-sm font-bold text-slate-900">Orden de Lab / Rx</span>
              <span className="text-[11px] text-slate-500">Pruebas Paraclínicas</span>
            </div>
          </button>

          {/* Constancia de Reposo */}
          <button
            type="button"
            id="doc-type-certificate"
            onClick={() => setDocType('certificate')}
            className={`p-3.5 rounded-xl border text-left transition-all flex flex-col justify-between cursor-pointer ${
              docType === 'certificate'
                ? 'bg-blue-50/70 border-blue-600 shadow-sm ring-1 ring-blue-600/30'
                : 'bg-white border-slate-200 hover:border-slate-300 hover:bg-slate-50'
            }`}
          >
            <div className="flex items-center justify-between mb-2">
              <div className={`p-2 rounded-lg ${docType === 'certificate' ? 'bg-blue-600 text-white' : 'bg-slate-100 text-slate-600'}`}>
                <Award className="w-4 h-4" />
              </div>
              {docType === 'certificate' && <CheckCircle2 className="w-4 h-4 text-blue-600" />}
            </div>
            <div>
              <span className="block text-sm font-bold text-slate-900">Constancia</span>
              <span className="text-[11px] text-slate-500">Reposo y Justificativo</span>
            </div>
          </button>
        </div>
      </div>

      {/* 2. PATIENT DETAILS BAR */}
      <div className="bg-white border border-slate-200 rounded-2xl p-5 shadow-sm space-y-4">
        <label className="text-xs font-bold text-slate-700 uppercase tracking-wider flex items-center gap-1.5">
          <User className="w-3.5 h-3.5 text-blue-600" />
          2. Datos del Paciente
        </label>

        <div className="grid grid-cols-1 sm:grid-cols-12 gap-4">
          {/* Nombre y Apellido */}
          <div className="sm:col-span-5 space-y-1">
            <label className="text-xs font-semibold text-slate-700">Nombre Completo del Paciente</label>
            <input
              id="patient-full-name"
              type="text"
              value={patient.fullName}
              onChange={(e) => setPatient({ ...patient, fullName: e.target.value })}
              placeholder="Ej. Dr. o Lic. Carlos Mendoza"
              className="w-full px-3.5 py-2.5 bg-slate-50 border border-slate-200 rounded-xl text-sm text-slate-900 focus:bg-white focus:outline-none focus:ring-2 focus:ring-blue-600/20 focus:border-blue-600 transition"
            />
          </div>

          {/* Tipo e Identificación (Cédula) */}
          <div className="sm:col-span-4 space-y-1">
            <label className="text-xs font-semibold text-slate-700">Cédula / Documento</label>
            <div className="flex gap-2">
              <select
                id="patient-id-type"
                value={patient.idType}
                onChange={(e) => setPatient({ ...patient, idType: e.target.value as any })}
                aria-label="Tipo de Documento de Identidad"
                className="w-16 px-2.5 py-2.5 bg-slate-50 border border-slate-200 rounded-xl text-sm font-bold text-slate-700 focus:bg-white focus:outline-none focus:ring-2 focus:ring-blue-600/20 focus:border-blue-600"
              >
                <option value="V">V-</option>
                <option value="E">E-</option>
                <option value="P">P-</option>
              </select>
              <input
                id="patient-national-id"
                type="text"
                value={patient.nationalId}
                onChange={(e) => setPatient({ ...patient, nationalId: e.target.value })}
                placeholder="12.345.678"
                className="w-full px-3.5 py-2.5 bg-slate-50 border border-slate-200 rounded-xl text-sm text-slate-900 focus:bg-white focus:outline-none focus:ring-2 focus:ring-blue-600/20 focus:border-blue-600 font-mono"
              />
            </div>
          </div>

          {/* Edad */}
          <div className="sm:col-span-3 space-y-1">
            <label className="text-xs font-semibold text-slate-700">Edad & Género</label>
            <div className="flex gap-2">
              <input
                id="patient-age"
                type="number"
                value={patient.age}
                onChange={(e) => setPatient({ ...patient, age: e.target.value })}
                placeholder="Años"
                className="w-20 px-3 py-2.5 bg-slate-50 border border-slate-200 rounded-xl text-sm text-slate-900 focus:bg-white focus:outline-none focus:ring-2 focus:ring-blue-600/20 focus:border-blue-600"
              />
              <select
                id="patient-gender"
                value={patient.gender}
                onChange={(e) => setPatient({ ...patient, gender: e.target.value as any })}
                aria-label="Género del paciente"
                className="w-full px-2 py-2.5 bg-slate-50 border border-slate-200 rounded-xl text-xs font-medium text-slate-700 focus:bg-white focus:outline-none focus:ring-2 focus:ring-blue-600/20 focus:border-blue-600"
              >
                <option value="M">Masculino</option>
                <option value="F">Femenino</option>
              </select>
            </div>
          </div>
        </div>

        {/* Alergias & Teléfono */}
        <div className="grid grid-cols-1 sm:grid-cols-12 gap-4 pt-2 border-t border-slate-100">
          <div className="sm:col-span-8 space-y-1">
            <div className="flex items-center justify-between">
              <label className="text-xs font-semibold text-slate-700 flex items-center gap-1">
                <ShieldAlert className="w-3.5 h-3.5 text-amber-500" />
                Alergias Conocidas (Se imprime en rojo en el récipe)
              </label>
              <span className="text-[11px] text-slate-400">Si no tiene, dejar 'Negadas'</span>
            </div>
            <input
              id="patient-allergies"
              type="text"
              value={patient.allergies}
              onChange={(e) => setPatient({ ...patient, allergies: e.target.value })}
              placeholder="Ej. Penicilina, AINEs, Sulfas (o 'Negadas')"
              className="w-full px-3.5 py-2 bg-slate-50 border border-slate-200 rounded-xl text-xs font-medium text-slate-900 focus:bg-white focus:outline-none focus:ring-2 focus:ring-blue-600/20 focus:border-blue-600"
            />
          </div>

          <div className="sm:col-span-4 space-y-1">
            <label className="text-xs font-semibold text-slate-700">Teléfono de Contacto</label>
            <input
              id="patient-phone"
              type="text"
              value={patient.phone || ''}
              onChange={(e) => setPatient({ ...patient, phone: e.target.value })}
              placeholder="0414-0000000"
              className="w-full px-3.5 py-2 bg-slate-50 border border-slate-200 rounded-xl text-xs text-slate-900 focus:bg-white focus:outline-none focus:ring-2 focus:ring-blue-600/20 focus:border-blue-600"
            />
          </div>
        </div>
      </div>

      {/* 3. CLINICAL NOTE (DICTATION / FREE TEXTAREA) */}
      <div className="bg-white border border-slate-200 rounded-2xl p-5 shadow-sm space-y-4">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 pb-2 border-b border-slate-100">
          <div>
            <div className="flex items-center gap-2">
              <label className="text-xs font-bold text-slate-800 uppercase tracking-wider flex items-center gap-1.5">
                <Sparkles className="w-3.5 h-3.5 text-blue-600" />
                3. Dictado Clínico por Voz o Texto Libre
              </label>
              <span className="px-2 py-0.5 rounded-full text-[10px] font-semibold bg-emerald-50 text-emerald-700 border border-emerald-200">
                Web Speech API Activa
              </span>
            </div>
            <p className="text-xs text-slate-500 mt-0.5">
              Dicta diagnósticos, fármacos e indicaciones con puntuación médica por voz. El motor Gemini estructurará la posología.
            </p>
          </div>

          {/* Dictation Controls Toolbar */}
          <div className="flex items-center gap-2 flex-wrap">
            {/* Language Selection */}
            <select
              id="speech-language-select"
              value={speechLang}
              onChange={(e) => setSpeechLang(e.target.value as any)}
              disabled={isListening}
              className="text-xs bg-slate-50 hover:bg-slate-100 border border-slate-200 text-slate-700 font-medium py-1.5 px-2 rounded-xl focus:outline-none focus:ring-1 focus:ring-blue-500 cursor-pointer disabled:opacity-60"
              title="Idioma del reconocimiento de voz"
            >
              <option value="es-VE">🇻🇪 Español (Venezuela)</option>
              <option value="es-419">🌎 Español (Latinoamérica)</option>
              <option value="es-ES">🇪🇸 Español (España)</option>
            </select>

            {/* Voice Commands Help Toggle */}
            <button
              type="button"
              id="btn-voice-commands-help"
              onClick={() => setShowVoiceHelp(!showVoiceHelp)}
              className={`p-1.5 text-xs rounded-xl border transition-colors cursor-pointer flex items-center gap-1 ${
                showVoiceHelp 
                  ? 'bg-blue-50 border-blue-300 text-blue-700' 
                  : 'bg-slate-50 hover:bg-slate-100 border-slate-200 text-slate-600'
              }`}
              title="Comandos de voz clínicos"
            >
              <HelpCircle className="w-3.5 h-3.5 text-blue-600" />
              <span className="text-[11px] font-medium hidden md:inline">Comandos</span>
            </button>

            {/* Clear Textarea Button */}
            {rawNote.trim() && (
              <button
                type="button"
                id="btn-clear-note"
                onClick={() => {
                  setRawNote('');
                  setInterimTranscript('');
                }}
                disabled={isListening}
                className="inline-flex items-center gap-1 px-2.5 py-1.5 text-xs font-semibold text-slate-500 hover:text-rose-600 hover:bg-rose-50 rounded-xl border border-slate-200 hover:border-rose-200 transition-colors cursor-pointer disabled:opacity-40"
                title="Limpiar texto de la nota para dictar desde cero"
              >
                <Trash2 className="w-3.5 h-3.5" />
                <span className="hidden sm:inline">Limpiar</span>
              </button>
            )}

            {/* Voice Dictation Trigger */}
            <button
              type="button"
              id="btn-voice-dictation"
              onClick={toggleSpeech}
              className={`inline-flex items-center gap-2 px-3.5 py-1.5 rounded-xl text-xs font-bold transition-all cursor-pointer shadow-xs ${
                isListening
                  ? 'bg-rose-600 hover:bg-rose-700 text-white animate-pulse shadow-md shadow-rose-200'
                  : 'bg-blue-600 hover:bg-blue-700 text-white'
              }`}
            >
              {isListening ? (
                <>
                  {/* Animated sound wave bars */}
                  <div className="flex items-center gap-0.5 h-3.5">
                    <span className="w-0.5 h-2.5 bg-white rounded-full animate-bounce [animation-delay:-0.3s]" />
                    <span className="w-0.5 h-3.5 bg-white rounded-full animate-bounce [animation-delay:-0.15s]" />
                    <span className="w-0.5 h-2 bg-white rounded-full animate-bounce" />
                  </div>
                  <MicOff className="w-3.5 h-3.5" />
                  <span>Detener Dictado</span>
                </>
              ) : (
                <>
                  <Mic className="w-3.5 h-3.5" />
                  <span>Dictar por Voz (Dr. Samir)</span>
                </>
              )}
            </button>
          </div>
        </div>

        {/* Voice Commands Cheat Sheet */}
        {showVoiceHelp && (
          <div className="p-3.5 bg-blue-50/70 border border-blue-200 rounded-xl text-xs text-blue-900 space-y-2 animate-fadeIn">
            <div className="flex items-center justify-between">
              <span className="font-bold flex items-center gap-1 text-blue-800">
                <Radio className="w-3.5 h-3.5 text-blue-600" />
                Comandos de Voz Médicos Reconocidos Automáticamente
              </span>
              <button 
                onClick={() => setShowVoiceHelp(false)}
                className="text-[11px] font-semibold text-blue-600 hover:text-blue-800 cursor-pointer"
              >
                Ocultar
              </button>
            </div>
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 text-[11px] font-mono text-slate-700">
              <div className="bg-white p-2 rounded-lg border border-blue-100">
                <span className="text-blue-700 font-bold block">"punto y aparte"</span>
                <span className="text-slate-500 font-sans">Doble salto de línea</span>
              </div>
              <div className="bg-white p-2 rounded-lg border border-blue-100">
                <span className="text-blue-700 font-bold block">"punto y seguido"</span>
                <span className="text-slate-500 font-sans">Inserta punto y espacio</span>
              </div>
              <div className="bg-white p-2 rounded-lg border border-blue-100">
                <span className="text-blue-700 font-bold block">"dos puntos" / "coma"</span>
                <span className="text-slate-500 font-sans">Inserta ':' o ','</span>
              </div>
              <div className="bg-white p-2 rounded-lg border border-blue-100">
                <span className="text-blue-700 font-bold block">"número uno / dos"</span>
                <span className="text-slate-500 font-sans">Crea lista: '1. ', '2. '</span>
              </div>
            </div>
          </div>
        )}

        {/* Live Speech Feedback Notice & Interim Transcription Stream */}
        {isListening && (
          <div className="p-3.5 bg-rose-50 border border-rose-200 rounded-xl text-xs text-rose-900 space-y-2 animate-fadeIn shadow-xs">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <span className="relative flex h-2.5 w-2.5">
                  <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-rose-400 opacity-75" />
                  <span className="relative inline-flex rounded-full h-2.5 w-2.5 bg-rose-600" />
                </span>
                <span className="font-semibold text-rose-800">
                  Micrófono activo • Escuchando al Dr. Samir Moucharrafie...
                </span>
              </div>
              <span className="font-mono text-[10px] text-rose-700 bg-rose-100 px-2 py-0.5 rounded-full font-bold uppercase">
                En Vivo (es-VE)
              </span>
            </div>

            {/* Interim Text Preview Bubble */}
            <div className="bg-white/90 border border-rose-200/80 rounded-lg p-2.5 text-xs text-slate-800 flex items-start gap-2">
              <Volume2 className="w-4 h-4 text-rose-600 shrink-0 mt-0.5" />
              <div className="flex-1 font-mono">
                {interimTranscript ? (
                  <span className="text-rose-950 font-medium">
                    {interimTranscript}
                    <span className="inline-block w-1.5 h-3 bg-rose-600 ml-1 animate-pulse" />
                  </span>
                ) : (
                  <span className="text-slate-400 italic">
                    Habla ahora: el audio se transcribe en tiempo real... (ej. "Diagnóstico hernia discal L4-L5...")
                  </span>
                )}
              </div>
            </div>
          </div>
        )}

        {/* Speech Error Banner */}
        {speechError && (
          <div className="p-3 bg-rose-50 border border-rose-200 rounded-xl text-xs text-rose-900 flex items-start gap-2">
            <AlertCircle className="w-4 h-4 text-rose-600 shrink-0 mt-0.5" />
            <div className="flex-1">
              <p className="font-semibold text-rose-800">Aviso de Micrófono</p>
              <p className="text-rose-700 mt-0.5">{speechError}</p>
            </div>
            <button
              type="button"
              onClick={() => setSpeechError(null)}
              className="text-rose-400 hover:text-rose-700 cursor-pointer font-bold text-xs"
            >
              ×
            </button>
          </div>
        )}

        {/* Large Textarea */}
        <div className="relative">
          <textarea
            id="clinical-note-textarea"
            ref={textareaRef}
            rows={7}
            value={rawNote}
            onChange={(e) => setRawNote(e.target.value)}
            placeholder="Escribe o dicta libremente: Diagnóstico, medicamentos con dosis y horarios, indicaciones generales, estudios a solicitar o reposo..."
            className={`w-full p-4 bg-slate-50 border rounded-xl text-sm leading-relaxed text-slate-900 focus:bg-white focus:outline-none focus:ring-2 transition resize-y font-sans ${
              isListening 
                ? 'border-rose-400 focus:ring-rose-500/20 focus:border-rose-600' 
                : 'border-slate-200 focus:ring-blue-600/20 focus:border-blue-600'
            }`}
          />
          <div className="absolute right-3 bottom-3 flex items-center gap-2 text-[11px] text-slate-400 font-mono">
            {isListening && (
              <span className="flex items-center gap-1 text-rose-600 font-semibold animate-pulse">
                <span className="w-1.5 h-1.5 rounded-full bg-rose-600" />
                Grabando
              </span>
            )}
            <span>{rawNote.length} caracteres</span>
          </div>
        </div>

        {/* Validation Warning */}
        {validationError && (
          <div className="p-3 bg-amber-50 border border-amber-200 rounded-xl text-xs text-amber-900 flex items-center gap-2">
            <AlertCircle className="w-4 h-4 text-amber-600 shrink-0" />
            <span>{validationError}</span>
          </div>
        )}
      </div>

      {/* 4. BOTTOM ACTION PANEL: PROCESAR E IMPRIMIR */}
      <div className="bg-slate-900 text-white rounded-2xl p-6 shadow-xl flex flex-col sm:flex-row items-center justify-between gap-5 border border-slate-800">
        <div className="space-y-1 text-center sm:text-left">
          <div className="flex items-center justify-center sm:justify-start gap-2">
            <h3 className="text-base font-bold text-white tracking-tight">
              Motor Magic Graphic listo para inyección
            </h3>
            <span className="px-2 py-0.5 text-[10px] font-bold uppercase tracking-wider rounded bg-blue-500/20 text-blue-300 border border-blue-400/30">
              Preserva Márgenes & Sellos
            </span>
          </div>
          <p className="text-xs text-slate-400 max-w-xl">
            Al procesar, Gemini estructura las entidades clínicas y Google Docs sustituye las etiquetas <code>&#123;&#123;PACIENTE&#125;&#125;</code>, <code>&#123;&#123;TRATAMIENTO&#125;&#125;</code> y <code>&#123;&#123;FECHA&#125;&#125;</code> devolviendo el PDF oficial listo para la impresora del consultorio.
          </p>
        </div>

        <button
          type="button"
          id="btn-process-print"
          onClick={handleProcessAndPrint}
          disabled={isProcessing}
          className="w-full sm:w-auto px-8 py-4 bg-blue-600 hover:bg-blue-500 active:bg-blue-700 text-white font-bold text-sm rounded-xl shadow-lg shadow-blue-600/30 flex items-center justify-center gap-2.5 transition-all transform hover:-translate-y-0.5 disabled:opacity-75 disabled:pointer-events-none cursor-pointer shrink-0"
        >
          {isProcessing ? (
            <>
              <RefreshCw className="w-5 h-5 animate-spin" />
              <span>{processingStage || 'Procesando...'}</span>
            </>
          ) : (
            <>
              <Printer className="w-5 h-5" />
              <span>Procesar e Imprimir</span>
            </>
          )}
        </button>
      </div>

      {/* Document Paper Preview Modal */}
      <DocumentPreviewModal
        document={processedDoc}
        isOpen={showPreviewModal}
        onClose={() => setShowPreviewModal(false)}
      />
    </div>
  );
};
